version: "3.9"

services:
  kenzie_pet:
    container_name: kenzie_pet
    image: kenzie_pet
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL="postgres://postgres:postgres@localhost:5431/kenzie_pet"
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5431:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kenzie_pet
